apiVersion: v1
kind: Pod
metadata:
  name: foss-app-with-init
  labels:
    app: web
  annotations:
    imageregistry: "https://hub.docker.com/"

spec:
  initContainers:
    - name: init-busybox
      image: busybox
      command: ["echo","This is an node app."]

    - name: init-nginx
      image: nginx
      command: ["sleep","10"]

  containers:
    - name: foss-web
      image: imnitin28/fossimage:1.0
      ports:
        - containerPort: 8080
