apiVersion: apps/v1
kind: Deployment
metadata:
  name: foss-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  # minReadySeconds: 10
  strategy:
    type: Recreate
    # rollingUpdate:
    #   maxUnavailable: 1
    #   maxSurge: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: imnitin28/fossimage:1.0
        ports:
        - containerPort: 8080