apiVersion: apps/v1
kind: Deployment
metadata:
  name: foss-app
  namespace: testing
spec:
  replicas: 3
  selector:
    matchLabels:
      app: foss-app
  template:
    metadata:
      labels:
        app: foss-app
    spec:
      containers:
      - name: node-foss-app
        image: imnitin28/fossimage:1.0
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "200Mi"
            cpu: "700m"
          requests:
            memory: "200Mi"
            cpu: "700m"
