apiVersion: v1
kind: Pod
metadata:
  name: ping-pod-to-cluster
  namespace: default
spec:
  containers:
  - name: busybox-image
    image: busybox
    command:
      - sleep
      - "1000"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
