apiVersion: v1
kind: Service
metadata:
  name: my-loadbalancer
  labels:
    app: nginx
  annotations:
    purpose: to show loadbalancer demo
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
    - nodePort: 30001
      targetPort: 80
      port: 80