# NodePort for external access
apiVersion: v1
kind: Service
metadata:
  name: my-nodeport-service
  labels:
    app: web
  annotations: 
    purpose: demo for nodeport network
spec:
  selector:
    app: web
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30040
      protocol: TCP
