apiVersion: v1
kind: Service
metadata:
# name nodeportregistered with DNS
  name: nodeport 
  # labels:
  #   app: web
  # annotations:
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31111
      protocol: TCP