apiVersion: v1
kind: Pod
metadata:
  name: foss-app-with-sidecar
  labels:
    app: web
  annotations:
    imageregistry: "https://hub.docker.com/"

spec:
  initContainers:
    - name: init-busybox
      image: busybox
      command: ["echo","This is an node app."]

    - name: init-nginx
      image: nginx
      command: ["sleep","10"]

  containers:
    - name: foss-web
      image: imnitin28/fossimage:1.0
      ports:
        - containerPort: 8080

    - image: busybox
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo echo $(ifconfig) 'This is a Sidecar container' >> /var/log/index.html; sleep 5;done"]
      name: sidecar-container