apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pie
spec:
  concurrencyPolicy: Allow
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: pie
            image: alpine
            command:
            - "sh"
            - "-c"
            - "echo 'scale=1000; 4*a(1)' | bc -l;sleep 2;"
