
apiVersion: v1
kind: Pod
metadata:
  name: welcome-pod
  labels:
    app: web
spec:
  containers:
    - name: foss-web
      image: imnitin28/fossimage:1.0
      ports:
        - containerPort: 8080
