apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
  labels: 
    app: nginx
  annotations:
    imageregistry: "https://hub.docker.com/"
spec:
  replicas: 3
  selector:
    app: nginx-1
  template:
    metadata:
      name: nginx
      # replicaController and pods are connected through this label - this label "nginx" should be same 
      # as of selector app name.
      labels:
        app: nginx-1
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
