apiVersion: v1
kind: Service
metadata:
  name: tcp-service
  labels:
    app: service-file-tcp
  annotations:
    purpose: assign target port to nginx-deployment
spec:
  selector:
    app: nginx-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376